> CC1<-read.csv("CC.csv")
> CC<-CC1[1:2000,]
> fit<-glm(Churn~.,data=CC[,-1], family="binomial")
> summary(fit)
> full<-glm(Churn~tenure*MonthlyCharges*TotalCharges,data=CC,family="binomial")
> null<-glm(Churn~1,data=CC,family=binomial)
> step(null,scope=list(lower=null,upper=full),direction="both")
> fit1<-glm(Churn ~ tenure + MonthlyCharges + tenure:MonthlyCharges, family = binomial, data = CC)
> summary(fit1)
> exp(coef(fit1))
> exp(cbind(OR=coef(fit1),confint(fit1)))
> library(car)
> vif(fit)
> vif(fit1)
> vif_values <- vif(fit)
> barplot(vif_values, main = "VIF Values", horiz = TRUE, col = "steelblue")
> abline(v = 5, lwd = 3, lty = 2)
> library(glmtoolbox)
> gvif(fit)
> gvif(fit1)
> anova(fit1,test="Chisq")
> cooks.distance<-cooks.distance(fit1)
> which(cooks.distance>1)
> library(survey)
> regTermTest(fit1,"tenure")
> regTermTest(fit1,"MonthlyCharges")
> regTermTest(fit1,"tenure:MonthlyCharges")
> library(ResourceSelection)
> hoslem.test(fit1$y,fitted(fit1),g=10)
> library(car)
> vif(fit1)
> library(pscl)
> pR2(fit1)
> library(effects)
> plot(allEffects(fit1))
> Telco<-read.csv("Telco.csv")
> Tfit<-glm(Churn~.,data=Telco[,-1], family="binomial")
> summary(Tfit)


